Added all 2.13 version files

diff --git a/usr/share/linex-ubuntu-puppet/sinc_puppet b/usr/share/linex-ubuntu-puppet/sinc_puppet
--- a/usr/share/linex-ubuntu-puppet/sinc_puppet
+++ b/usr/share/linex-ubuntu-puppet/sinc_puppet
@@ -2,8 +2,120 @@
 # Script para tratar de realizar la sincronización del cliente puppet
 # Colocar en /etc/network/if-up.d/ para que se ejecute al levantar el interfaz de red
 # Esteban M. Navas Martín
-# Modificado: 15/02/2015
-# Modificado: 19/05/2016
+# Fecha última modificación: 30/11/2016
+
+export DEBIAN_FRONTEND=noninteractive
+export VERSION=2.13
+
+SCRIPT=`basename "$0"`
+
+function print_version {
+	echo "$SCRIPT $VERSION"
+}
+
+function print_help {
+        echo "$SCRIPT $VERSION"
+        echo "Automated sinc puppet client"
+        echo ""
+        echo "Usage: $0 [OPTIONS]"
+        echo "Recognized options:"
+        echo "  -h               display this help and exit"
+        echo "  -v               display $SCRIPT version and exit"
+        echo "  -f               force $SCRIPT on SPLAYLIMIT"
+        echo "  -f now           force $SCRIPT now"
+        echo "  -r               renew cert client"
+        echo ""
+}
+
+function solveapterrors {
+
+  idioma=$LC_ALL
+  export LC_ALL=C
+
+  apt-get check 1>/dev/null 2>/tmp/apterrors
+
+  if [ -s /tmp/apterrors ]; then
+     grep "Unmet dependencies. Try using -f." /tmp/apterrors && apt-get -yf install && dpkg --configure -a && apt-get -y autoremove
+     grep "dpkg was interrupted, you must manually run 'dpkg --configure -a' to correct the problem." /tmp/apterrors && dpkg --configure -a && apt-get -yf install && apt-get -y autoremove
+     grep -E 'Encountered a section with no Package: header|Problem with MergeList ' /tmp/apterrors && rm -rf /var/lib/apt/lists/
+  fi
+
+  export LC_ALL=$idioma
+}
+
+function dosync {
+  if [ "$1" == "-f" ] && [ "$2" == "now" ]; then
+     echo "Conexión con servidor de puppet. Sincronizando puppet....." | logger -s -t $0
+     puppet agent --onetime --no-daemonize >/dev/null 2>&1
+     if [ $? -eq "0" ]; then
+        echo "Sistema PUPPET correcto" | logger -s -t $0
+        exit 0
+     fi
+  else
+     echo "Conexión con servidor de puppet." | logger -s -t $0
+     echo "Esperando un tiempo máximo de $SPLAYLIMIT para sincronizar puppet....." | logger -s -t $0
+     puppet agent --onetime --no-daemonize --splay --splaylimit $SPLAYLIMIT >/dev/null 2>&1
+     if [ $? -eq "0" ]; then
+        echo "Sistema PUPPET correcto" | logger -s -t $0
+        exit 0
+     fi
+  fi
+}
+
+
+# Leer y procesar argumentos
+while getopts ":f: rvh" opt
+do
+    case $opt in
+        v ) print_version
+	    exit 0
+	    ;;
+        h ) print_help
+ 	    exit 0
+	    ;;
+        f)  force="-f"
+            now=$OPTARG
+            ;;
+        r)  renew="-r"
+            ;;
+        \? ) echo "Opcion invalida -$OPTARG"
+             exit 1
+	     ;;
+        : )  force="-f"
+	     now=""
+    esac
+done
+shift $((OPTIND-1))
+
+# Mostrar ayuda si un caracter no deseado es introducido##
+if [ -n "$1" ]; then
+    print_help
+fi
+
+# Matamos procesos detenidos
+stopped_processes=$(ps auwx | awk 'NR>1 && $8 ~ "T" {print $2}')
+if [ "$stopped_processes" ]; then kill -9 $stopped_processes; fi
+
+# Matamos todos los procesos de sinc_puppet excepto el último que se haya
+sinc_puppet_processes=$(pgrep -c sinc_puppet)
+if [ "$sinc_puppet_processes" -gt "1" ]; then kill -9 $(pgrep sinc_puppet | head -n -1); fi
+
+# Nos aseguramos de que sólo exista una instancia de sinc_puppet corriendo
+lockfile=/tmp/sincpuppet
+
+# Eliminar fichero de bloqueo al salir
+trap "lockfile-remove $lockfile; exit" INT TERM EXIT
+
+lockfile-check $lockfile
+if [ $? -eq 0 ] ; then
+    # Si existe el fichero de bloqueo
+    # echo >&2 "lock not acquired, giving up: $lockfile"
+    exit 1
+else
+    # Si no existe el fichero de bloqueo
+    lockfile-create $lockfile         # Creamos el fichero de bloqueo
+    # echo "lock acquired: $lockfile"
+fi
 
 # Controlamos la ejecución manual o automática de sinc_puppet
 ENABLE=yes
@@ -14,6 +126,11 @@ if [ "$ENABLE" == "no" ] || [ ! "$ENABLE" ]; then
   exit 0
 fi
 
+# Si no se ha definido el parámetro WAITFORCERT en el fichero de configuración, le establecemos un valor por defecto
+if [ -z "$WAITFORCERT" ]; then
+   WAITFORCERT="30"
+fi
+
 # Número máximo de segundos sin sincronizar con el servidor puppet
 MAXTIME=`expr $INTERVAL \* 3600`
 
@@ -22,15 +139,14 @@ uno=$(stat -c %Y  /var/log/syslog)
 dos=$(stat -c %Y /var/lib/puppet/state/state.yaml)
 dife=$((uno-dos))
 
-# Aseguramos paquetes
-dpkg --configure -a && apt-get -yf install && apt-get -y autoremove
+solveapterrors
 
 echo "La última sincronización con PUPPET fue hace: "$(($dife / 3600)) "horas" | logger -s -t $0
 echo "Intervalo de sincronización con PUPPET: $INTERVAL horas" | logger -s -t $0
 echo
 
-# Salimos si no se ha alcanzado el tiempo máximo sin sincronizar con PUPPET
-if [ $dife -lt $MAXTIME ]; then exit 0; fi
+# Salimos si no se ha alcanzado el tiempo máximo sin sincronizar con PUPPET o no se ha forzado la ejecución
+if [ $dife -lt $MAXTIME ] || [ $# -eq 1 ] && [ "$force" != "-f" ] || [ $# -eq 1 ] && [ "$renew" != "-r" ]; then exit 0; fi
 
 ping -c 1 $PING_SERVER >/dev/null 2>&1
 ERROR=$?
@@ -46,31 +162,39 @@ done
 
 if [ $MAX -eq $PING_TRIES ]; then
  echo "Imposible contactar con el servidor....." | logger -s -t $0
- exit 5
+ exit $MAX
 fi
 
 # Activamos puppet, por si estuviera desactivado
 puppet agent --enable
 
+if [ "$renew" == "-r" ]; then
+   uuid=$(/usr/bin/uuidgen -t) && sed -i "s/certname=.*/certname=$uuid/" /usr/share/linex-ubuntu-puppet/puppet.conf
+   find /var/lib/puppet/ssl/ -type f -name *.pem -not -name ca.pem -not -name crl.pem -exec rm -f {} \;
+   dosync $force $now
+fi
+
+
+# Obtenemos el uuid del fichero puppet.conf
+uuid=$(sed -n 's|certname=\(.*\)|\1|p' /usr/share/linex-ubuntu-puppet/puppet.conf)
+
 # Si no existe el certificado del cliente, ejecutamos puppet tratando de recibir un certificado
-test -f /var/lib/puppet/ssl/certs/$(hostname -f).pem
-if [ $? -eq "1" ]; then
-   puppet agent --test --waitforcert 60 >/dev/null 2>&1
-   exit 0
+if [ -z "$uuid" ]; then
+   uuid=$(/usr/bin/uuidgen -t) && sed -i "/server=puppetinstituto/a certname=$uuid" /usr/share/linex-ubuntu-puppet/puppet.conf
+   echo "Se ha generado un nuevo uuid para este host: $uuid" | logger -s -t $0
+   find /var/lib/puppet/ssl/ -type f -name *.pem -not -name ca.pem -not -name crl.pem -exec rm -f {} \;
+
+   dosync $force $now
 fi
 
-#Si ha estado más de MAXTIME segundos sin sincronizar con puppet
-if [ $dife -gt  $MAXTIME ]; then
- echo "Conexión con servidor de puppet. Esperando $SPLAYLIMIT para puppet....." | logger -s -t $0
- puppet agent --onetime --no-daemonize --splay --splaylimit $SPLAYLIMIT
+test -f /var/lib/puppet/ssl/certs/$uuid.pem
+if [ $? -eq "0" ]; then
 
- while [ $? -eq "1" ]; do
-   test -f /var/lib/puppet/state/puppetdlock && rm -f /var/lib/puppet/state/puppetdlock
-   rm -rf /var/lib/puppet/ssl/certs/$(hostname -f).pem
-   echo "FALLO Puppet. Nuevo intento en 30 segundos" | logger -s -t $0
-   puppet agent --test --waitforcert 60 >/dev/null 2>&1
- done
+   dosync $force $now
+else
+   [ -f /var/lib/puppet/state/puppetdlock ] && rm -f /var/lib/puppet/state/puppetdlock
+   uuid=$(/usr/bin/uuidgen -t) && sed -i "s/certname=.*/certname=$uuid/" /usr/share/linex-ubuntu-puppet/puppet.conf
+   find /var/lib/puppet/ssl/ -type f -name *.pem -not -name $uuid.pem -not -name ca.pem -not -name crl.pem -exec rm -f {} \;
+
+   dosync $force $now
 fi
-echo "Sistema PUPPET correcto" | logger -s -t $0 
-
-exit 0
